import type {
  ActiveSetup,
  ExploreTone,
  Gear,
  OriginalSongDetail,
  SavedTone,
  ToneDetail,
  UserProfile,
} from './types';

export const user: UserProfile = {
  name: 'Attila Feher',
  email: 'attila@tonekid.app',
  memberSince: 'May 12, 2026',
  tier: 'free',
};

export const initialGear: Gear[] = [
  { id: 'g1', type: 'guitar', brand: 'Yamaha', model: 'Pacifica 012', isActive: true },
  { id: 'a1', type: 'amp', brand: 'Boss', model: 'Katana' },
  { id: 'mfx1', type: 'multifx', brand: 'Line 6', model: 'Helix Floor', isActive: true },
];

export const activeSetup: ActiveSetup = {
  guitarId: 'g1',
  rigId: 'mfx1',
};

export const initialSavedTones: SavedTone[] = [
  {
    id: 'hotel-california',
    song: 'Hotel California',
    artist: 'Eagles',
    partType: 'Solo',
    gearSummary: 'Yamaha Pacifica 012, Helix Floor',
  },
];

const grayShades = ['#E8E8EA', '#DCDCDF', '#D2D2D6', '#C8C8CC', '#BFBFC4', '#E2E2E5', '#D7D7DB'];

export const exploreTones: ExploreTone[] = [
  {
    id: 'master-of-puppets',
    song: 'Master of Puppets',
    artist: 'Metallica',
    partType: 'Riff',
    toneType: 'Distorted',
    likes: 1240,
    placeholderShade: grayShades[0],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/b8/5a/82/b85a8259-60d9-bfaa-770a-2baac8380e87/858978005196.png/600x600bb.jpg',
    artworkDominantColor: '#C49A3A',
    genres: ['Metal', 'Rock'],
  },
  {
    id: 'enter-sandman',
    song: 'Enter Sandman',
    artist: 'Metallica',
    partType: 'Riff',
    toneType: 'Distorted',
    likes: 980,
    placeholderShade: grayShades[1],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/2e/94/95/2e9495d7-dfe3-ddc8-87ef-6ef797a60218/850007452056.png/600x600bb.jpg',
    artworkDominantColor: '#2A2A2E',
    genres: ['Metal', 'Rock'],
  },
  {
    id: 'sweet-child-o-mine',
    song: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    partType: 'Solo',
    toneType: 'Distorted',
    likes: 1567,
    placeholderShade: grayShades[2],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/56/47/b7/5647b700-6b9d-9e72-ec9f-51140b6d4492/00602567673781.rgb.jpg/600x600bb.jpg',
    artworkDominantColor: '#B0856B',
    genres: ['Rock'],
  },
  {
    id: 'hotel-california',
    song: 'Hotel California',
    artist: 'Eagles',
    partType: 'Solo',
    toneType: 'Clean',
    likes: 2103,
    placeholderShade: grayShades[3],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/88/16/2c/88162c3d-46db-8321-61f3-3a47404cfe76/075596050920.jpg/600x600bb.jpg',
    artworkDominantColor: '#C97A3F',
    genres: ['Rock', 'Country'],
  },
  {
    id: 'creeping-death',
    song: 'Creeping Death',
    artist: 'Metallica',
    partType: 'Riff',
    toneType: 'Distorted',
    likes: 712,
    placeholderShade: grayShades[4],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/1d/7d/88/1d7d88ea-3bfd-9f20-2c86-630a32aac634/dj.mapicmzf.png/600x600bb.jpg',
    artworkDominantColor: '#7A2E2A',
    genres: ['Metal'],
  },
  {
    id: 'comfortably-numb',
    song: 'Comfortably Numb',
    artist: 'Pink Floyd',
    partType: 'Solo',
    toneType: 'Distorted',
    likes: 1842,
    placeholderShade: grayShades[5],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/3e/17/ec/3e17ec6d-f980-c64f-19e0-a6fd8bbf0c10/886445635850.jpg/600x600bb.jpg',
    artworkDominantColor: '#8C2F2F',
    genres: ['Rock', 'Blues'],
  },
  {
    id: 'stairway-to-heaven',
    song: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    partType: 'Solo',
    toneType: 'Clean',
    likes: 1928,
    placeholderShade: grayShades[6],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music5/v4/16/de/e3/16dee335-173b-57ce-80b5-dadf684c0b33/dj.oblporhs.jpg/600x600bb.jpg',
    artworkDominantColor: '#9B6E3F',
    genres: ['Rock'],
  },
  {
    id: 'sultans-of-swing',
    song: 'Sultans of Swing',
    artist: 'Dire Straits',
    partType: 'Solo',
    toneType: 'Clean',
    likes: 1334,
    placeholderShade: grayShades[0],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music/47/c3/21/mzi.ciyzkqao.jpg/600x600bb.jpg',
    artworkDominantColor: '#D85F7E',
    genres: ['Rock', 'Blues'],
  },
  {
    id: 'wonderwall',
    song: 'Wonderwall',
    artist: 'Oasis',
    partType: 'Riff',
    toneType: 'Clean',
    likes: 868,
    placeholderShade: grayShades[2],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music113/v4/04/92/e0/0492e08b-cbcc-9969-9ad6-8f5a0888068c/5051961007107.jpg/600x600bb.jpg',
    artworkDominantColor: '#5B7AA5',
    genres: ['Indie', 'Pop', 'Rock'],
  },
  {
    id: 'black-dog',
    song: 'Black Dog',
    artist: 'Led Zeppelin',
    partType: 'Riff',
    toneType: 'Distorted',
    likes: 904,
    placeholderShade: grayShades[5],
    artworkUrl:
      'https://is1-ssl.mzstatic.com/image/thumb/Music5/v4/16/de/e3/16dee335-173b-57ce-80b5-dadf684c0b33/dj.oblporhs.jpg/600x600bb.jpg',
    artworkDominantColor: '#9B6E3F',
    genres: ['Rock', 'Blues'],
  },
];

export const hotelCaliforniaToneDetail: ToneDetail = {
  id: 'hotel-california',
  song: 'Hotel California',
  artist: 'Eagles',
  partType: 'Solo',
  matchScore: 90,
  rig: 'Line 6 Helix Floor / LT / Rack',
  rigSubtitle: 'Effects chain preset (use with your physical amp)',
  artworkUrl:
    'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/88/16/2c/88162c3d-46db-8321-61f3-3a47404cfe76/075596050920.jpg/600x600bb.jpg',
  keyToneElements: [
    'Smooth overdrive from the amp and pedal combination.',
    'Tape delay for ambient repeats.',
    'Phaser for modulation texture.',
    'Spring reverb for ambience.',
    'Touch-sensitive attack for expressive playing.',
  ],
  eqGuidance:
    'Focus on midrange clarity. Keep bass moderate to avoid muddiness, push mids slightly for vocal-like singing tone, and use treble to taste so the solo cuts through without harshness.',
  eqCallout:
    'Do not adjust the EQ on the overdrive pedal to prevent conflicting settings with the amp tone stack.',
  signalFlow: {
    source: 'Guitar',
    deviceLabel: 'Line 6 Helix Floor / LT / Rack',
    effects: [
      { name: 'Minotaur (Klon Centaur)', color: 'green' },
      { name: 'Transistor Tape (Echoplex)', color: 'blue' },
      { name: 'Script Phase (Phase 90)', color: 'pink' },
    ],
  },
  ampModel: {
    name: 'US Deluxe Nrm (Fender Deluxe Reverb)',
    channel: 'Crunch',
    cabinet: 'Open Back 1x12',
    master: '7/10',
    description:
      'A warm, breakup-friendly American voicing that captures the bell-like clean tone and the natural overdrive that defines the solo.',
    eqCallout:
      'Set Bass around 5, Mids 7, Treble 6. Push Drive to where the amp begins to break up gently.',
  },
  effectBlocks: {
    beforeAmp: [
      {
        id: 'minotaur',
        number: 1,
        name: 'Minotaur (Klon Centaur)',
        replaces: 'Klon Centaur',
        type: 'Overdrive',
        color: 'green',
        tags: [
          { label: 'Critical for tone', variant: 'critical' },
          { label: 'Exact', variant: 'exact' },
        ],
        description:
          'Transparent overdrive used to add harmonic richness and singing sustain to the amp without coloring the EQ.',
        params: [
          { label: 'Gain', value: '6' },
          { label: 'Tone', value: '5' },
          { label: 'Output', value: '7' },
        ],
        callout: 'Pushes the amp into its sweet spot for a more aggressive sound.',
      },
    ],
    afterAmp: [
      {
        id: 'transistor-tape',
        number: 2,
        name: 'Transistor Tape (Echoplex)',
        replaces: 'Echoplex EP-3',
        type: 'Delay',
        color: 'blue',
        tags: [
          { label: 'Critical for tone', variant: 'critical' },
          { label: 'Exact', variant: 'exact' },
        ],
        description:
          'Warm tape-style delay that lends ambient repeats and a subtle modulation that gives the solo its hypnotic, dreamlike character.',
        params: [
          { label: 'Time', value: '450' },
          { label: 'Feedback', value: '5' },
          { label: 'Mix', value: '4' },
        ],
        callout: 'Adds depth and ambiance to the tone.',
      },
      {
        id: 'script-phase',
        number: 3,
        name: 'Script Phase (Phase 90)',
        replaces: 'MXR Phase 90',
        type: 'Modulation',
        color: 'pink',
        tags: [{ label: 'Similar', variant: 'similar' }],
        description:
          'Subtle four-stage phaser that adds movement and texture beneath the melodic lines without overpowering them.',
        params: [
          { label: 'Rate', value: '3' },
          { label: 'Depth', value: '4' },
        ],
        callout: 'Solos only — Enable during solos for added sustain.',
        disabled: true,
        enableContext: 'Enable for solos',
      },
      {
        id: 'dynamic-room',
        number: 4,
        name: 'Dynamic Room',
        replaces: 'Spring Reverb',
        type: 'Reverb',
        color: 'teal',
        tags: [{ label: 'Similar', variant: 'similar' }],
        description:
          'Short, plate-like reverb that sits the guitar inside a sense of physical space without washing out the attack.',
        params: [
          { label: 'Decay', value: '2.4' },
          { label: 'Mix', value: '3' },
        ],
        callout: 'Provides sustain and tightens the attack for riff clarity.',
      },
      {
        id: 'noise-gate',
        number: 5,
        name: 'Noise Gate',
        replaces: 'Stock gate',
        type: 'Enhancement',
        color: 'gray',
        tags: [{ label: 'Similar', variant: 'similar' }],
        description:
          'Light noise gate to suppress hum from the overdriven amp during pauses while keeping note sustain intact.',
        params: [
          { label: 'Threshold', value: '-58' },
          { label: 'Decay', value: '50' },
        ],
        callout: 'Keeps the signal clean and tight during palm muting.',
      },
    ],
  },
  physicalAmpSettings: {
    eqGuidance: "Set the amp's EQ to match the original tone, focusing on mid and treble for clarity.",
    knobs: [
      { label: 'Gain', value: '8' },
      { label: 'Bass', value: '5.5' },
      { label: 'Mid', value: '7.5' },
      { label: 'Treble', value: '7' },
    ],
  },
  limitations: [
    {
      label: 'n/a',
      severity: 'nice',
      body: 'The tone may lack some of the harmonic richness that a real Klon can provide.',
      workaround: 'Use the overdrive with slightly higher gain settings to compensate.',
    },
  ],
  toneMatchAnalysis:
    'This preset closely matches the original tone with a high-gain overdrive and a reverb effect. However, the original amp characteristics cannot be replicated exactly since the user is using an effects-only setup.',
  setupNotes: [
    'Connect your guitar to the input of the Helix.',
    'Set the overdrive and compression levels as specified.',
    'Adjust the noise gate threshold to eliminate unwanted noise.',
    'Set the reverb and delay to taste, enabling delay only during solos.',
  ],
  playingTips: [
    'Use aggressive pick attack for clarity and articulation.',
    'Maintain a tight wrist for precision in riffing.',
    'Focus on palm muting for a punchy sound in the lower notes.',
  ],
  userGuitarSettings: {
    guitarName: 'Yamaha Pacifica 012',
    tone: '7-8',
    volume: '8-9',
    bullets: [
      'High-gain tone with singing sustain.',
      'Bright and articulate attack with clear note separation.',
      'Tight, percussive riff clarity with harmonic-rich overdrive.',
    ],
  },
};

export const toneDetailById: Record<string, ToneDetail> = {
  'hotel-california': hotelCaliforniaToneDetail,
};

export const songDetailById: Record<string, OriginalSongDetail> = {
  'master-of-puppets': {
    id: 'master-of-puppets',
    song: 'Master of Puppets',
    artist: 'Metallica',
    album: 'Master of Puppets',
    year: '1986',
    partType: 'Riff',
    toneType: 'Distorted',
    difficulty: 'Advanced',
    tuning: 'E Standard',
    tempoBpm: 212,
    songKey: 'E minor',
    stringGauge: '.010–.046',
    pickingTechnique: 'Heavy palm-muted alternate picking',
    version: 'Studio',
    originalGuitar: 'ESP James Hetfield Signature',
    originalPickups: 'EMG-81 (bridge), EMG-60 (neck)',
    pickupSelector: 'Bridge',
    guitarSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Tone', value: '10' },
    ],
    originalAmp: 'Mesa/Boogie Mark IIC+',
    ampSettings: [
      { label: 'Gain', value: '8' },
      { label: 'Bass', value: '4' },
      { label: 'Mid', value: '6' },
      { label: 'Treble', value: '7' },
      { label: 'Presence', value: '6' },
      { label: 'Master', value: '5' },
    ],
    signalChain: [
      { name: 'Tube Screamer (clean boost)', color: 'green' },
      { name: 'ISO Noise Gate', color: 'gray' },
    ],
    notes: 'Tight palm-muted picking with edge-of-the-pick attack. Aim for clarity, not fuzz.',
    cabinet: 'Mesa 4x12 cabinet',
    toneCharacter: [
      'tight and percussive',
      'scooped mids',
      'aggressive palm muting',
      'high-gain saturation',
      'razor-sharp articulation',
      'chunky low end',
      'dry, minimal ambience',
      'fast alternate picking clarity',
      'metallic bite',
      'powerful attack',
    ],
    difficultyReasons: [
      'fast alternate picking at high tempo',
      'precise palm muting and right-hand control',
      'tight synchronization between left and right hand',
      'complex rhythm changes and downpicking endurance',
    ],
  },
  'enter-sandman': {
    id: 'enter-sandman',
    song: 'Enter Sandman',
    artist: 'Metallica',
    album: 'Metallica (Black Album)',
    year: '1991',
    partType: 'Riff',
    toneType: 'Distorted',
    difficulty: 'Intermediate',
    tuning: 'E Standard',
    tempoBpm: 123,
    songKey: 'E minor',
    stringGauge: '.010–.046',
    pickingTechnique: 'Palm-muted downpicking on the main riff',
    version: 'Studio',
    originalGuitar: 'ESP MX-250',
    originalPickups: 'EMG-81 / EMG-60',
    pickupSelector: 'Bridge',
    guitarSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Tone', value: '8' },
    ],
    originalAmp: 'Mesa/Boogie Mark IIC+',
    ampSettings: [
      { label: 'Gain', value: '7' },
      { label: 'Bass', value: '5' },
      { label: 'Mid', value: '5' },
      { label: 'Treble', value: '6' },
      { label: 'Master', value: '5' },
    ],
    signalChain: [
      { name: 'Wah (clean intro)', color: 'pink' },
      { name: 'Noise Gate', color: 'gray' },
    ],
  },
  'sweet-child-o-mine': {
    id: 'sweet-child-o-mine',
    song: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    album: 'Appetite for Destruction',
    year: '1987',
    partType: 'Solo',
    toneType: 'Distorted',
    difficulty: 'Advanced',
    tuning: 'E Standard',
    tempoBpm: 125,
    songKey: 'D♭ major',
    stringGauge: '.011–.048',
    pickingTechnique: 'Pick with finger-rolls into bends',
    version: 'Studio',
    originalGuitar: 'Gibson Les Paul Standard',
    originalPickups: 'Seymour Duncan Alnico II Pro',
    pickupSelector: 'Bridge',
    guitarSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Tone', value: '8' },
    ],
    originalAmp: 'Marshall JCM 800',
    ampSettings: [
      { label: 'Gain', value: '7' },
      { label: 'Bass', value: '6' },
      { label: 'Mid', value: '6' },
      { label: 'Treble', value: '7' },
      { label: 'Presence', value: '5' },
    ],
    signalChain: [
      { name: 'MXR Stereo Chorus', color: 'pink' },
      { name: 'Boss DD delay (light)', color: 'blue' },
    ],
    notes: 'Slash style: dig in with the bridge pickup, let the amp do the work.',
  },
  'hotel-california': {
    id: 'hotel-california',
    song: 'Hotel California',
    artist: 'Eagles',
    album: 'Hotel California',
    year: '1976',
    partType: 'Solo',
    toneType: 'Clean',
    difficulty: 'Advanced',
    tuning: 'E Standard',
    tempoBpm: 75,
    songKey: 'B minor',
    stringGauge: '.010–.046',
    pickingTechnique: 'Pick with vocal-style bends and vibrato',
    version: 'Studio',
    originalGuitar: 'Gibson EDS-1275 (Don Felder)',
    originalPickups: 'Humbuckers',
    pickupSelector: 'Bridge',
    guitarSettings: [
      { label: 'Volume', value: '9' },
      { label: 'Tone', value: '7' },
    ],
    originalAmp: 'Fender Tweed Deluxe',
    ampSettings: [
      { label: 'Volume', value: '6' },
      { label: 'Bass', value: '5' },
      { label: 'Mid', value: '7' },
      { label: 'Treble', value: '6' },
      { label: 'Reverb', value: '4' },
    ],
    signalChain: [
      { name: 'Klon Centaur (overdrive)', color: 'green' },
      { name: 'Echoplex EP-3 (delay)', color: 'blue' },
      { name: 'MXR Phase 90', color: 'pink' },
    ],
    notes: 'Sustained, vocal-style bends. Light tape delay carries the phrasing.',
  },
  'creeping-death': {
    id: 'creeping-death',
    song: 'Creeping Death',
    artist: 'Metallica',
    album: 'Ride the Lightning',
    year: '1984',
    partType: 'Riff',
    toneType: 'Distorted',
    difficulty: 'Advanced',
    tuning: 'E Standard',
    tempoBpm: 220,
    songKey: 'E minor',
    stringGauge: '.010–.046',
    pickingTechnique: 'Aggressive downpicking + gallop',
    version: 'Studio',
    originalGuitar: 'Gibson Flying V',
    originalPickups: 'EMG-81',
    pickupSelector: 'Bridge',
    guitarSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Tone', value: '10' },
    ],
    originalAmp: 'Mesa/Boogie Mark IIB',
    ampSettings: [
      { label: 'Gain', value: '8' },
      { label: 'Bass', value: '4' },
      { label: 'Mid', value: '5' },
      { label: 'Treble', value: '7' },
    ],
    signalChain: [
      { name: 'Tube Screamer boost', color: 'green' },
      { name: 'Noise Gate', color: 'gray' },
    ],
  },
  'comfortably-numb': {
    id: 'comfortably-numb',
    song: 'Comfortably Numb',
    artist: 'Pink Floyd',
    album: 'The Wall',
    year: '1979',
    partType: 'Solo',
    toneType: 'Distorted',
    difficulty: 'Advanced',
    tuning: 'E Standard',
    tempoBpm: 63,
    songKey: 'B minor',
    stringGauge: '.010–.048 (Gilmour)',
    pickingTechnique: 'Pick attack with wide string bends and vibrato',
    version: 'Studio',
    originalGuitar: 'Fender "Black Strat" (David Gilmour)',
    originalPickups: 'Single-coil (bridge)',
    pickupSelector: 'Bridge',
    guitarSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Tone', value: '6' },
    ],
    originalAmp: 'Hiwatt DR103',
    ampSettings: [
      { label: 'Master', value: '7' },
      { label: 'Bass', value: '5' },
      { label: 'Mid', value: '7' },
      { label: 'Treble', value: '6' },
      { label: 'Presence', value: '6' },
    ],
    signalChain: [
      { name: 'Big Muff Pi', color: 'green' },
      { name: 'Electric Mistress (flange)', color: 'pink' },
      { name: 'Binson Echorec (delay)', color: 'blue' },
    ],
    notes: 'Sustain comes from the Muff + long delay tail, not gain on the amp.',
  },
  'stairway-to-heaven': {
    id: 'stairway-to-heaven',
    song: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    year: '1971',
    partType: 'Solo',
    toneType: 'Clean',
    difficulty: 'Advanced',
    tuning: 'E Standard',
    tempoBpm: 82,
    songKey: 'A minor',
    stringGauge: '.009–.042',
    pickingTechnique: 'Hybrid pick + fingers; fast pull-offs in the solo',
    version: 'Studio',
    originalGuitar: 'Fender Telecaster (solo) / Gibson Les Paul (live)',
    originalPickups: 'Single-coil (bridge)',
    pickupSelector: 'Bridge',
    guitarSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Tone', value: '7' },
    ],
    originalAmp: 'Supro 1690T (studio)',
    ampSettings: [
      { label: 'Volume', value: '8' },
      { label: 'Bass', value: '5' },
      { label: 'Treble', value: '7' },
    ],
    signalChain: [{ name: 'Plate reverb (studio)', color: 'teal' }],
  },
  'sultans-of-swing': {
    id: 'sultans-of-swing',
    song: 'Sultans of Swing',
    artist: 'Dire Straits',
    album: 'Dire Straits',
    year: '1978',
    partType: 'Solo',
    toneType: 'Clean',
    difficulty: 'Intermediate',
    tuning: 'E Standard',
    tempoBpm: 149,
    songKey: 'D minor',
    stringGauge: '.009–.042',
    pickingTechnique: 'Fingerstyle — no pick, thumb-and-finger attack',
    version: 'Studio',
    originalGuitar: 'Fender Stratocaster',
    originalPickups: 'Single-coils',
    pickupSelector: 'Position 2 (Neck + Middle)',
    guitarSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Tone', value: '8' },
    ],
    originalAmp: 'Vox AC30',
    ampSettings: [
      { label: 'Normal', value: '4' },
      { label: 'Top Boost', value: '6' },
      { label: 'Bass', value: '5' },
      { label: 'Treble', value: '5' },
    ],
    signalChain: [{ name: 'Mild spring reverb', color: 'teal' }],
    notes: 'Knopfler fingerstyle — no pick. Pluck soft, let the AC30 chime.',
  },
  'wonderwall': {
    id: 'wonderwall',
    song: 'Wonderwall',
    artist: 'Oasis',
    album: '(What\'s the Story) Morning Glory?',
    year: '1995',
    partType: 'Riff',
    toneType: 'Clean',
    difficulty: 'Beginner',
    tuning: 'E Standard',
    capo: '2nd fret',
    tempoBpm: 87,
    songKey: 'F♯ minor (capo 2)',
    stringGauge: '.011–.052 (acoustic)',
    pickingTechnique: 'Strummed open chords, light pick',
    version: 'Studio',
    originalGuitar: 'Epiphone Casino (acoustic on record)',
    originalPickups: 'P-90 (Casino)',
    pickupSelector: 'Neck',
    guitarSettings: [
      { label: 'Volume', value: '8' },
      { label: 'Tone', value: '7' },
    ],
    originalAmp: 'Acoustic (direct) + Vox AC30 doubling',
    ampSettings: [
      { label: 'Volume', value: '4' },
      { label: 'Bass', value: '5' },
      { label: 'Treble', value: '4' },
    ],
    signalChain: [{ name: 'Light room reverb', color: 'teal' }],
  },
  'black-dog': {
    id: 'black-dog',
    song: 'Black Dog',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    year: '1971',
    partType: 'Riff',
    toneType: 'Distorted',
    difficulty: 'Intermediate',
    tuning: 'E Standard',
    tempoBpm: 90,
    songKey: 'A major',
    stringGauge: '.009–.042 (Page)',
    pickingTechnique: 'Pick attack with bluesy bends; call-and-response',
    version: 'Studio',
    originalGuitar: 'Gibson Les Paul',
    originalPickups: 'Humbuckers',
    pickupSelector: 'Bridge',
    guitarSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Tone', value: '8' },
    ],
    originalAmp: 'Marshall Super Lead 1959 (cranked)',
    ampSettings: [
      { label: 'Volume', value: '10' },
      { label: 'Bass', value: '6' },
      { label: 'Mid', value: '5' },
      { label: 'Treble', value: '7' },
      { label: 'Presence', value: '5' },
    ],
    signalChain: [{ name: 'Direct-injected (DI) on verses', color: 'gray' }],
  },
};
